# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'xmpp-ios-obj-c' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!
pod 'XMPPFramework', '~> 3.7.0'
  # Pods for xmpp-ios-obj-c

end
